# Generated by Django 2.2.2 on 2019-10-21 13:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.TextField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watermeter',
            fields=[
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('altitude', models.IntegerField(blank=True, default=None, null=True)),
                ('owner', models.TextField(max_length=250, primary_key=True, serialize=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('pointer_value', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_pointer', models.BooleanField(default=False)),
                ('tally_counter_1', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_1', models.BooleanField(default=False)),
                ('tally_counter_2', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_2', models.BooleanField(default=False)),
                ('tally_counter_3', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_3', models.BooleanField(default=False)),
                ('tally_counter_4', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_4', models.BooleanField(default=False)),
                ('tally_counter_5', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_5', models.BooleanField(default=False)),
                ('tally_counter_6', models.IntegerField(blank=True, default=None, null=True)),
                ('flag_tally_counter_6', models.BooleanField(default=False)),
                ('watermeter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.Watermeter')),
            ],
        ),
    ]
